var x = prompt("enter your number")
if(x>=80)
    document.write("A+")
else if(x>=70 && x<80 )
    document.write("A")
else if(x>=65 && x<70 )
    document.write("A-")
else if(x>=60 && x<65 )
    document.write("b+")
else if(x>=55 && x<60 )
    document.write("b-")
else if(x>=40 && x<55 )
    document.write("c")
else 
    document.write("Fail")
